# Generated by Django 4.2.3 on 2023-07-06 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_location_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='データ更新日'),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='result',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日'),
        ),
    ]
